name: spec
on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Ruby and the gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
